# Generated by Django 5.1.3 on 2024-12-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biceps',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='forearm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='glutes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shoulders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que este usuario pertenece.', related_name='userprofile_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='userprofile_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
