# Generated by Django 5.1.3 on 2024-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalSuplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='manual/nutritionalsuplementsimages')),
            ],
        ),
        migrations.CreateModel(
            name='Suplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manual/suplementsimages')),
            ],
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='question',
        ),
        migrations.AddField(
            model_name='nutritionalsuplements',
            name='nutritional_suplements',
            field=models.ManyToManyField(to='manual.suplements'),
        ),
    ]
