# Generated by Django 5.1.3 on 2024-12-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='manual/')),
            ],
        ),
        migrations.DeleteModel(
            name='Encyclopedia',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('pierna', 'Pierna'), ('brazo', 'Brazo'), ('hombro', 'Hombro'), ('abdomen', 'Abdomen')], max_length=50),
        ),
    ]
