# Generated by Django 5.1.3 on 2024-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_nutritionalsuplements_suplements_delete_nutrition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manual/musclesimages')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_groups',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(to='manual.muscles'),
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
