# Generated by Django 5.1.3 on 2024-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_manual_delete_encyclopedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='manual/exercises/videos'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manual/exercises/images'),
        ),
    ]
