# Generated by Django 5.1.3 on 2024-12-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_rename_muscles_muscle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(to='manual.tag'),
        ),
    ]
